#!/bin/bash
echo "Creating ~/.vimrc"

echo "
execute pathogen#infect()

let mapleader=','
set number
syntax on
:imap jk <Esc>
:imap <C-L> <Esc>
set background=dark
let g:solarized_termtrans=1
colorscheme zenburn
set wildmenu
set showcmd

set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR>


:set noexpandtab
:set copyindent
:set preserveindent
:set softtabstop=0
:set shiftwidth=4
:set tabstop=4
:set autoindent
filetype plugin indent on

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:airline#extensions#tabline#enabled = 1
map <C-c> :bd<cr>

map <C-n> :NERDTreeFocus<CR>
map <C-m> :NERDTreeToggle<CR>

vnoremap <silent> # :s/^/#/<cr>:noh<cr>
vnoremap <silent> -# :s/^#//<cr>:noh<cr>

set noswapfile
set cursorline

nmap <C-i> :TagbarToggle<CR>
nmap <C-l> :TagbarOpen fj<CR>
nmap <C-h> <C-w>h
let g:tagbar_show_linenumbers = 1
" > ~/.vimrc

echo "Done creating ~/.vimrc"

echo "set-option -g mouse on" > ~/.tmux.conf
echo "Done creating ~/.tmux.conf"

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
cd ~/.vim/bundle
git clone git://github.com/tpope/vim-unimpaired.git
git clone git://github.com/tpope/vim-sensible.git
git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline
git clone https://github.com/kien/ctrlp.vim.git bundle/ctrlp.vim
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
git clone https://github.com/posva/vim-vue.git ~/.vim/bundle/vim-vue
git clone https://github.com/majutsushi/tagbar
wget http://www.vim.org/scripts/download_script.php?src_id=10873
mv download_script.php?src_id=10873 autoclose.vim
mkdir ~/.vim/colors
cd  ~/.vim/colors
wget https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim
echo export TERM=screen-256color >> ~/.bashrc
source ~/.bashrc
cd ~
